name: Build Fiche
on:
  push:
    branches:
      - master
jobs:
  push:
    name: Fiche building...
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: fiche
          path: fiche
